# DEVELOPMENT
version: '3'

services:
  api:
    build: ./
    restart: always
    ports:
      - 4001:4001
    volumes:
      - /home/app/node_modules
      - './:/home/app'
    env_file:
      - ./.env_development
    command: 'npm run dev'
